BEGIN;

CREATE TABLE IF NOT EXISTS position_ingestion_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_at TIMESTAMPTZ NOT NULL UNIQUE,
    leaderboard_captured_at TIMESTAMPTZ,
    category VARCHAR(32),
    time_period VARCHAR(16),
    top_n INTEGER
);

ALTER TABLE position_ingestion_batches
    ADD COLUMN IF NOT EXISTS leaderboard_captured_at TIMESTAMPTZ;

ALTER TABLE position_ingestion_batches
    ADD COLUMN IF NOT EXISTS category VARCHAR(32),
    ADD COLUMN IF NOT EXISTS time_period VARCHAR(16),
    ADD COLUMN IF NOT EXISTS top_n INTEGER;

CREATE TABLE IF NOT EXISTS smart_money_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id VARCHAR(80) NOT NULL,
    outcome VARCHAR(16) NOT NULL,
    capital_usd NUMERIC(18, 2) NOT NULL,
    score NUMERIC(6, 2) NOT NULL,
    has_coverage BOOLEAN NOT NULL,
    trader_count INTEGER NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL,
    position_ingestion_batch_id BIGINT REFERENCES position_ingestion_batches (id)
);

ALTER TABLE smart_money_scores
    ADD COLUMN IF NOT EXISTS position_ingestion_batch_id BIGINT
        REFERENCES position_ingestion_batches (id);

COMMIT;

-- These may scan populated append-only tables, so build them without blocking writes.
-- Run this file with psql/autocommit because concurrent index creation cannot be wrapped in
-- a transaction block.
-- If a previous concurrent build was interrupted, remove only its invalid artifact so
-- IF NOT EXISTS cannot hide it. The psql command executes generated DROP statements.
SELECT format(
    'DROP INDEX CONCURRENTLY IF EXISTS %I.%I',
    index_namespace.nspname,
    index_class.relname
)
FROM pg_index AS index_state
JOIN pg_class AS index_class ON index_class.oid = index_state.indexrelid
JOIN pg_namespace AS index_namespace ON index_namespace.oid = index_class.relnamespace
WHERE index_namespace.nspname = current_schema()
  AND NOT index_state.indisvalid
  AND index_class.relname IN (
      'ix_trader_rankings_cohort_snapshot',
      'ix_positions_snapshot_wallet_market',
      'ix_position_batches_cohort_snapshot',
      'ix_smart_money_scores_snapshot_market',
      'ix_smart_money_scores_position_batch',
      'uq_smart_money_score_position_batch_market'
  )
\gexec

CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_trader_rankings_cohort_snapshot
    ON trader_rankings (category, time_period, captured_at, rank);

CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_positions_snapshot_wallet_market
    ON positions (captured_at, wallet_address, condition_id, outcome);

CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_position_batches_cohort_snapshot
    ON position_ingestion_batches (category, time_period, top_n, captured_at);

CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_smart_money_scores_snapshot_market
    ON smart_money_scores (captured_at, condition_id, outcome);

CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_smart_money_scores_position_batch
    ON smart_money_scores (position_ingestion_batch_id);

CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS uq_smart_money_score_position_batch_market
    ON smart_money_scores (position_ingestion_batch_id, condition_id, outcome)
    WHERE position_ingestion_batch_id IS NOT NULL;
