BEGIN;

CREATE TABLE IF NOT EXISTS position_ingestion_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_at TIMESTAMPTZ NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS smart_money_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_id VARCHAR(80) NOT NULL,
    outcome VARCHAR(16) NOT NULL,
    capital_usd NUMERIC(18, 2) NOT NULL,
    score NUMERIC(6, 2) NOT NULL,
    has_coverage BOOLEAN NOT NULL,
    trader_count INTEGER NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_trader_rankings_cohort_snapshot
    ON trader_rankings (category, time_period, captured_at, rank);

CREATE INDEX IF NOT EXISTS ix_positions_snapshot_wallet_market
    ON positions (captured_at, wallet_address, condition_id, outcome);

CREATE INDEX IF NOT EXISTS ix_smart_money_scores_snapshot_market
    ON smart_money_scores (captured_at, condition_id, outcome);

COMMIT;
